# The theoretically calculated OCS-transmon readout spectrum as a function of $n_g$.

The familiar Cooper-pair-box Hamiltonian with a slight generalization:
$$
\hat{H}_{CPB} = 4E_{C}(\hat{n} - n_g + \frac{P - 1}{4})^2 - E_J cos(\hat{\phi}).
$$

An OCS transmon coupled to a single linear readout mode is described by the following Hamiltonian [7, 13]:
$$
\hat{H} = \hat{H}_{CPB} + \hbar \omega_{r} \hat{a}^{\dagger} \hat{a} + \hbar g \hat{n} (\hat{a} + \hat{a}^{\dagger})
$$

In [5]:
"""
Import Library
"""
import numpy as np
import qutip
import matplotlib.pyplot as plt

### Let's define the constant first.

#### The Plank Constant (Unit: $m^2 \cdot kg / s$)
$$
h = 6.62607015 \cdot 10^{-34} 
$$

In [6]:
# 常數
h = 6.626e-34  # Planck constant
hbar = h / (2 * np.pi)
omega_r = 9.202e9 * (2 * np.pi)  # rad/s
E_J = 6.14e9 * h  # J
E_C = 356e6 * h  # J

# 最大基態數目
n_max = 10

# 建立基底
basis = [qutip.basis(n_max, n) for n in range(n_max)]
print(basis)


[Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [

### Create basis with the number of Cooper pairs

$$
\hat{n} |n \rangle = n |n\rangle
$$