In [2]:
from qutip import *

import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(Qobj())

Quantum object: dims=[[1], [1]], shape=(1, 1), type='scalar', dtype=Dense
Qobj data =
[[nan]]


In [4]:
print(Qobj([[1],[2],[3],[4],[5]]))


Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [5]:
x = np.array([[1, 2, 3, 4, 5]])
print(Qobj(x))


Quantum object: dims=[[1], [5]], shape=(1, 5), type='bra', dtype=Dense
Qobj data =
[[1. 2. 3. 4. 5.]]


In [6]:
r = np.random.rand(4, 4)
print(Qobj(r))


Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0.82345414 0.51820259 0.43919608 0.2630169 ]
 [0.89867397 0.40794008 0.95874385 0.47235762]
 [0.97292441 0.1209792  0.46473127 0.77449306]
 [0.93307582 0.25855102 0.66198301 0.94666533]]
